---
# tasks file for docker-registry
- name: Log into DockerHub
  docker_login:
    username: azizbenhaha
    password: mydockerhub
- name: Push to docker hub
  docker_image:
    name: azizbenhaha/livraison
    repository: azizbenhaha/livraison
    tag: latest
    source: local
    push: yes
