---
# tasks file for docker-registry
- name: Log into DockerHub
  docker_login:
    username: aminegongi
    password: 271998271998
    email: amine.gongi@esprit.tn
- name: Push to docker hub
  docker_image:
    name: aminegongi/cd_lab
    repository: aminegongi/cd_lab
    tag: latest
    source: local
    push: yes
