---
# tasks file for docker
- name: create image docker
  docker_image:
    name: aminegongi/cd_lab
    build:
     path: /var/lib/jenkins/workspace/lab1
     pull: no
    source: build
    state: present
    force_source: true
- name: run container docker
  docker_container:
    name: ag_myapp_container
    image: aminegongi/cd_lab:latest
    state: started
    recreate: true
    ports:
     - "4200:80"   
